use_frameworks!

platform :ios, '8.0'

target 'demo_Aspects_Example' do
  pod 'demo_Aspects', :path => '../'
  pod 'Aspects'

  target 'demo_Aspects_Tests' do
    inherit! :search_paths

    
  end
end
